const I18N = {
  es: {
    skip: "Ir al contenido",
    brand: "Roberto Verdecia Sánchez",
    nav_home: "Inicio",
    nav_work: "Trabajo",
    nav_how: "Cómo",
    nav_quote: "Cotizar",
    nav_care: "Cuidado",
    nav_contact: "Contacto",
    menu: "Menú",
    close: "Cerrar menú",
    lang_to: "Cambiar a English",
    theme_to_light: "Modo claro",
    theme_to_dark: "Modo oscuro",
    top_aria: "Volver arriba",
    hero_h: "Soy Roberto, programador de sitios web",
    hero_sub: "Diseño y programo tu sitio completo, de la idea a estar en línea. Conóceme, mira mi trabajo y arma tu cotización al instante.",
    hero_cta: "Armar mi cotización",
    hero_secondary: "Ver trabajo",
    hero_board_title: "Pizarra de ejemplo",
    hero_board_note: "Esto se actualiza de verdad en el cotizador.",
    hb_pages: "Páginas",
    hb_forms: "Formularios",
    hb_seo: "Aparecer en Google",
    hb_seo_v: "Esencial",
    about_h: "Sobre mí",
    about_1: "Soy Roberto Verdecia Sánchez, programador de sitios web. Convierto una idea de negocio en un sitio claro que la gente entiende y usa sin pensarlo.",
    about_2: "Llevo más de 6 años construyendo productos reales: plataformas de datos y sistemas de gestión que usan equipos todos los días. Esa experiencia la traigo a tu web: orden, velocidad y decisiones de diseño que se notan en el resultado.",
    about_3: "Me encargo de todo el sitio, de principio a fin: diseño, desarrollo y dejarlo publicado. Te hablo sin tecnicismos y no escribo código hasta que apruebas la propuesta.",
    about_4: "Profesionalismo, detalle y fiabilidad: cada proyecto lo trato con el mismo cuidado que si fuera mío.",
    about_stat_1_n: "6+ años",
    about_stat_1_t: "creando productos reales de software",
    about_stat_2_n: "De la idea al aire",
    about_stat_2_t: "diseño, desarrollo y publicación en una sola persona",
    about_stat_3_n: "1–4 semanas",
    about_stat_3_t: "para tener tu sitio publicado",
    offer_h: "Qué te construyo",
    offer_p: "El centro son proyectos de corta duración. Siempre responsive: se ve y se usa bien en el móvil y en el escritorio.",
    offer_short_h: "Sitios cortos",
    offer_short_p: "Landing o 3 a 8 páginas. Servicios, horarios, contacto, formularios. Listo para que tus clientes te encuentren.",
    offer_sys_h: "CRM, SaaS, gestión o tienda",
    offer_sys_p: "Estos proyectos no caben en un cotizador automático. Escríbeme por WhatsApp y analizamos si es viable.",
    offer_sys_cta: "Hablar por WhatsApp",
    work_h: "Trabajo representativo",
    work_p: "Por NDA no publico nombres de cliente confidenciales. Estas capturas y piezas son sitios o plantillas que ya construí, para que veas el tipo de problema que resuelvo.",
    work_1_t: "Iglesia parroquial",
    work_1_p: "Sitio de comunidad: horarios, ministerios y una llegada clara para quien busca un lugar.",
    work_2_t: "Barbería con reserva",
    work_2_p: "Presencia de autor y reserva por WhatsApp, sin fricción de formularios eternos.",
    work_3_t: "Tienda con pedido",
    work_3_p: "Catálogo, carrito y confirmación por WhatsApp. Pedido simple, sin pasarela inventada.",
    work_4_t: "Gimnasio local",
    work_4_p: "Planes, horarios y un llamado a inscribirse que se entiende en segundos.",
    work_5_t: "Cafetería",
    work_5_p: "Carta, ambiente y ubicación: lo que un visitante necesita antes de ir.",
    work_6_t: "Dulcería / retail",
    work_6_p: "Vitrina de productos y contacto directo. Hecho para decidir rápido.",
    how_h: "Cómo trabajo contigo",
    how_1_h: "Te escucho",
    how_1_p: "Me cuentas tus objetivos, a quién te diriges y qué debe incluir el sitio.",
    how_2_h: "Te propongo",
    how_2_p: "Te muestro una propuesta visual y funcional. No escribo código hasta que la apruebes.",
    how_3_h: "Lo construyo",
    how_3_p: "Desarrollo el sitio siguiendo el plan que acordamos. Siempre responsive.",
    how_4_h: "Te lo entrego",
    how_4_p: "Publico tu web. Dominio y hosting los contratas tú; yo te asisto si lo pides.",
    quote_h: "Arma tu cotización",
    quote_p: "Marca lo que necesitas. El rango se escribe en la pizarra al instante. No es precio final: yo lo reviso y te confirmo.",
    quote_interview: "Un CRM, SaaS, sistema de gestión o tienda online no se cotiza a ciegas. Escríbeme por WhatsApp y analizamos si el proyecto es viable.",
    quote_wa: "Contactar por WhatsApp",
    quote_range: "Estimado",
    quote_not_final: "No es precio final. Dominio y hosting van aparte.",
    quote_empty: "—",
    quote_send_hint: "¿Listo? Envíame tu cotización y te confirmo el precio.",
    quote_send_wa: "Enviar por WhatsApp",
    quote_send_mail: "Enviar por correo",
    host_h: "Dominio y hosting",
    host_intro: "Son dos cosas separadas de tu web, y ninguna es complicada. Las contratas tú, a tu nombre, para que siempre tengas el control. Yo te acompaño en elegirlas, comprarlas y dejar el sitio publicado.",
    host_domain_h: "El dominio: tu dirección en internet",
    host_domain_p: "Es el nombre que la gente escribe para llegar a ti, como tunegocio.com. Es igual que la dirección de tu local: única y tuya. Por ejemplo: cafeteria-lucia.com o barberiajuan.com.",
    host_domain_cost: "Suele costar entre $10 y $15 al año.",
    host_hosting_h: "El hosting: dónde vive tu web",
    host_hosting_p: "Es el espacio en internet donde se guarda tu web para que esté abierta las 24 horas. Piénsalo como el alquiler del local donde montas tu negocio: sin él, tu web no puede estar en línea.",
    host_hosting_cost: "Según el proyecto, desde unos pocos dólares al mes.",
    host_foot: "Ninguno de los dos entra en el rango de construcción. Te asesoro para que elijas bien y no pagues de más.",
    care_h: "Cuando el sitio ya está vivo",
    care_p: "Un sitio en internet no se queda quieto: el navegador cambia, aparecen fallos y la seguridad hay que mantenerla. El cuidado no es opcional; eliges cómo lo hacemos, no si lo hacemos. Los montos son orientativos.",
    care_note: "El mantenimiento cuida el sitio ya construido: correcciones, actualizaciones, copias de seguridad y ajustes pequeños. No es desarrollo nuevo. Las funciones o secciones nuevas se cotizan aparte una vez terminado el sitio.",
    care_1_h: "Cuidado puntual",
    care_1_price: "desde $15 / mes",
    care_1_p: "Lo esencial para que tu sitio no se caiga ni se quede atrás.",
    care_1_b1: "Copia de seguridad mensual",
    care_1_b2: "Actualizaciones de seguridad",
    care_1_b3: "Reviso que todo siga en línea",
    care_2_h: "Mejora continua",
    care_2_price: "desde $25 / mes",
    care_2_p: "Todo lo anterior y, además, cambios pequeños cada mes.",
    care_2_b1: "Todo lo del plan puntual",
    care_2_b2: "Cupo de cambios de texto e imágenes",
    care_2_b3: "Revisión de velocidad y enlaces rotos",
    care_3_h: "Acompañamiento",
    care_3_price: "desde $50 / mes",
    care_3_p: "Para negocios que se mueven rápido y necesitan prioridad.",
    care_3_b1: "Todo lo de mejora continua",
    care_3_b2: "Atención prioritaria en la misma semana",
    care_3_b3: "Plan de mejoras cada mes",
    faq_h: "Preguntas frecuentes",
    faq_1_q: "¿Qué necesito de ti?",
    faq_1_a: "Textos, datos del negocio y, si los tienes, fotos, logo y enlaces. Si no, te ayudo a estructurarlo.",
    faq_2_q: "¿El sitio será responsive?",
    faq_2_a: "Sí. Todo lo que te entrego se ve y se usa en móvil, tablet y escritorio. No es un extra: va incluido.",
    faq_3_q: "¿Incluye dominio o hosting?",
    faq_3_a: "No. Van por tu cuenta. Te asesoro y te ayudo a contratarlos y a publicar.",
    faq_4_q: "¿Y si necesito una tienda o un sistema grande?",
    faq_4_a: "CRM, SaaS, gestión o tienda online salen del cotizador. Escríbeme por WhatsApp y vemos si el proyecto es viable.",
    contact_h: "Cuéntame qué necesitas",
    contact_p: "Te preparo una propuesta con el desglose que armaste arriba.",
    label_name: "Nombre",
    label_email: "Correo",
    label_message: "Mensaje",
    ph_message: "Cuéntame el contexto, plazos o dudas…",
    send: "Enviarme tu mensaje",
    wa: "Escríbeme por WhatsApp",
    hint: "Al enviar, se abre tu correo con el desglose listo. Dominio y hosting no van en el rango.",
    footer: "Todos los derechos reservados.",
    yes: "Sí",
    no: "No",
    "q.type": "Tipo de proyecto",
    "q.type.web": "Sitio Web",
    "q.type.landing": "Página de aterrizaje (Landing)",
    "q.type.shop": "Tienda online",
    "q.type.system": "CRM / SaaS / Sistema de gestión",
    "q.type.web.desc": "Un sitio de varias secciones para presentar tu negocio: quién eres, qué ofreces y cómo contactarte.",
    "q.type.landing.desc": "Una sola página enfocada en un objetivo: que el visitante te contacte, reserve o compre algo puntual.",
    "q.type.shop.desc": "Una tienda con catálogo y pedidos. Por su complejidad no se cotiza aquí: lo vemos por WhatsApp.",
    "q.type.system.desc": "Un sistema a medida (paneles, usuarios, datos). No entra en el cotizador: lo analizamos por WhatsApp.",
    "q.pages": "¿Qué tan grande es tu sitio?",
    "q.pages.help": "Elige lo que más se parezca a lo que necesitas. Son secciones dentro del mismo sitio.",
    "q.pages.one": "Todo en una página",
    "q.pages.one.desc": "Una sola página con todo. Ideal para empezar.",
    "q.pages.basic": "Sitio básico · unas 3 páginas",
    "q.pages.basic.desc": "Inicio, Servicios y Contacto.",
    "q.pages.standard": "Sitio completo · unas 5 páginas",
    "q.pages.standard.desc": "Inicio, Sobre ti, Servicios, Galería y Contacto.",
    "q.pages.wide": "Sitio amplio · 7 a 8 páginas",
    "q.pages.wide.desc": "Lo anterior más blog, preguntas o precios.",
    "q.landingOnly": "Una sola página",
    "q.forms": "Formularios",
    "q.forms.help": "Un formulario recoge datos de tus clientes: contacto, reservas o pedidos. Si dudas, con 1 suele bastar.",
    "q.admin": "Administración del sitio",
    "q.admin.help": "¿Quieres poder editar el contenido tú mismo, sin depender de mí?",
    "q.admin.none": "No la necesito",
    "q.admin.basic": "Básica: editar textos e imágenes",
    "q.admin.advanced": "Avanzada: productos, publicaciones o usuarios",
    "q.seo": "Aparecer en Google (SEO)",
    "q.seo.none": "Sin SEO (no te buscan en Google)",
    "q.seo.basic": "Esencial (títulos y descripción)",
    "q.seo.local": "Local (que te hallen en tu ciudad)",
    "q.seo.advanced": "Completo (para competir)",
    "q.seo.tip_aria": "Qué es SEO y qué incluye cada nivel",
    "q.seo.tip_what": "SEO es cómo Google te encuentra cuando alguien busca lo que ofreces. Sin eso, tu web existe, pero casi nadie llega desde el buscador.",
    "q.seo.tip_none": "Sin SEO: no preparo el sitio para buscadores.",
    "q.seo.tip_basic": "Esencial: títulos, descripción y lo mínimo para que Google te indexe.",
    "q.seo.tip_local": "Local: además, te oriento para que te hallen en tu ciudad o barrio.",
    "q.seo.tip_advanced": "Completo: estructura, velocidad y contenido para competir con otros negocios.",
    "q.design": "Diseño",
    "q.design.preset": "Predefinido / plantilla",
    "q.design.scratch": "Desde cero",
    "q.design.help": "Predefinido parte de una plantilla cuidada; desde cero es un diseño único para ti.",
    "q.identity": "Identidad (logo y colores)",
    "q.identity.defined": "Ya la tengo",
    "q.identity.create": "Hay que crearla",
    "q.identity.help": "¿Tienes logo y colores de marca, o los creamos?",
    "q.theme": "Tema del sitio",
    "q.theme.light": "Solo claro",
    "q.theme.both": "Claro y oscuro",
    "q.theme.help": "¿Quieres que tu web ofrezca modo claro y también modo oscuro?",
    "q.languages": "Idiomas",
    "q.languages.one": "Uno",
    "q.languages.multi": "Dos o más",
    "q.languages.help": "¿Tu sitio debe estar en más de un idioma?",
    "q.images": "¿Tus imágenes están listas?",
    "q.images.help": "Nos referimos a fotos o gráficos ya recortados y optimizados para web.",
    "q.images.ready": "Sí, ya están listas",
    "q.images.process": "No, prepáralas tú",
    "q.images.help.ready": "Perfecto: uso tus imágenes tal cual, sin costo extra.",
    "q.images.help.process": "Yo ajusto formato, tamaño y peso para que carguen rápido y se vean nítidas (trabajo adicional).",
    "q.maintenance": "Mantenimiento después",
    "q.maintenance.help": "Siempre hay que hacerlo. El mantenimiento no es desarrollo nuevo: las funciones o secciones nuevas se cotizan aparte.",
    "q.maintenance.light": "Cuidado puntual",
    "q.maintenance.mid": "Mejora continua",
    "q.maintenance.full": "Acompañamiento",
    select: "Selecciona",
  },
  en: {
    skip: "Skip to content",
    brand: "Roberto Verdecia Sánchez",
    nav_home: "Home",
    nav_work: "Work",
    nav_how: "How",
    nav_quote: "Quote",
    nav_care: "Care",
    nav_contact: "Contact",
    menu: "Menu",
    close: "Close menu",
    lang_to: "Switch to Español",
    theme_to_light: "Light mode",
    theme_to_dark: "Dark mode",
    top_aria: "Back to top",
    hero_h: "I’m Roberto, a website programmer",
    hero_sub: "I design and build your whole site, from the idea to going live. Get to know me, see my work, and build your quote in a minute.",
    hero_cta: "Build my quote",
    hero_secondary: "See work",
    hero_board_title: "Sample board",
    hero_board_note: "The real board updates in the quote section.",
    hb_pages: "Pages",
    hb_forms: "Forms",
    hb_seo: "Show up on Google",
    hb_seo_v: "Essential",
    about_h: "About me",
    about_1: "I’m Roberto Verdecia Sánchez, a website programmer. I turn a business idea into a clear site people understand and use without thinking.",
    about_2: "I’ve spent 6+ years building real products: data platforms and management systems that teams use every day. I bring that experience to your site: order, speed, and design decisions you can feel in the result.",
    about_3: "I handle the whole site end to end: design, development, and getting it published. I speak without jargon and I don’t write code until you approve the plan.",
    about_4: "Professionalism, care, and reliability: I treat every project with the same care as if it were my own.",
    about_stat_1_n: "6+ years",
    about_stat_1_t: "building real software products",
    about_stat_2_n: "Idea to live",
    about_stat_2_t: "design, development, and publishing in one person",
    about_stat_3_n: "1–4 weeks",
    about_stat_3_t: "to get your site published",
    offer_h: "What I build for you",
    offer_p: "The core is short-cycle work. Always responsive: it works on a phone and on a desktop.",
    offer_short_h: "Short sites",
    offer_short_p: "A landing page or 3–8 pages. Services, hours, contact, forms. Ready so your clients can find you.",
    offer_sys_h: "CRM, SaaS, ops, or a store",
    offer_sys_p: "These projects don’t fit an automatic quote. Message me on WhatsApp and we’ll check if it’s viable.",
    offer_sys_cta: "Talk on WhatsApp",
    work_h: "Representative work",
    work_p: "NDAs mean I can’t publish confidential client names. These pieces are sites or templates I already built, so you can see the kind of problem I solve.",
    work_1_t: "Parish church",
    work_1_p: "A community site: service times, ministries, and a clear welcome for someone looking for a place.",
    work_2_t: "Barbershop booking",
    work_2_p: "Author-led presence and WhatsApp booking, without a long form in the way.",
    work_3_t: "Shop with orders",
    work_3_p: "Catalog, cart, and WhatsApp confirmation. A simple order path — no fake checkout.",
    work_4_t: "Local gym",
    work_4_p: "Plans, hours, and a join CTA you understand in seconds.",
    work_5_t: "Café",
    work_5_p: "Menu, atmosphere, and location: what a visitor needs before they go.",
    work_6_t: "Sweets / retail",
    work_6_p: "A product window and a direct contact path. Built for a fast decision.",
    how_h: "How I work with you",
    how_1_h: "I listen",
    how_1_p: "You tell me your goals, who you serve, and what the site must include.",
    how_2_h: "I propose",
    how_2_p: "I show you a visual and functional plan. I don’t write code until you approve it.",
    how_3_h: "I build it",
    how_3_p: "I develop the site from the plan we agreed. Always responsive.",
    how_4_h: "I deliver",
    how_4_p: "I publish your site. You contract domain and hosting; I help if you ask.",
    quote_h: "Build your quote",
    quote_p: "Mark what you need. The range writes itself on the board instantly. It is not a final price: I review it and confirm.",
    quote_interview: "A CRM, SaaS, ops system, or online store is not quoted blindly. Message me on WhatsApp and we’ll check if the project is viable.",
    quote_wa: "Contact on WhatsApp",
    quote_range: "Estimate",
    quote_not_final: "Not a final price. Domain and hosting are separate.",
    quote_empty: "—",
    quote_send_hint: "Ready? Send me your quote and I’ll confirm the price.",
    quote_send_wa: "Send on WhatsApp",
    quote_send_mail: "Send by email",
    host_h: "Domain and hosting",
    host_intro: "These are two separate things from your site, and neither is complicated. You contract them, in your name, so you always keep control. I guide you to choose them, buy them, and get the site published.",
    host_domain_h: "The domain: your address on the internet",
    host_domain_p: "It’s the name people type to reach you, like yourbusiness.com. It’s just like your shop’s address: unique and yours. For example: lucia-cafe.com or johnbarber.com.",
    host_domain_cost: "It usually costs between $10 and $15 a year.",
    host_hosting_h: "The hosting: where your site lives",
    host_hosting_p: "It’s the space on the internet where your site is stored so it stays open 24 hours a day. Think of it as the rent for the place where you set up your business: without it, your site can’t be online.",
    host_hosting_cost: "Depending on the project, from a few dollars a month.",
    host_foot: "Neither one is part of the build range. I advise you so you choose well and don’t overpay.",
    care_h: "After the site is live",
    care_p: "A site online doesn’t sit still: browsers change, bugs appear, and security must be kept up. Care is not optional; you choose how we do it, not whether we do it. Amounts are indicative.",
    care_note: "Maintenance looks after the site already built: fixes, updates, backups, and small tweaks. It is not new development. New features or sections are quoted separately once the site is finished.",
    care_1_h: "Light care",
    care_1_price: "from $15 / month",
    care_1_p: "The essentials so your site doesn’t go down or fall behind.",
    care_1_b1: "Monthly backup",
    care_1_b2: "Security updates",
    care_1_b3: "I check it stays online",
    care_2_h: "Steady improvement",
    care_2_price: "from $25 / month",
    care_2_p: "Everything above, plus small monthly changes.",
    care_2_b1: "Everything in Light care",
    care_2_b2: "An allotment for text and image changes",
    care_2_b3: "Speed and broken-link review",
    care_3_h: "Full accompaniment",
    care_3_price: "from $50 / month",
    care_3_p: "For businesses that move fast and need priority.",
    care_3_b1: "Everything in Steady improvement",
    care_3_b2: "Priority, same-week attention",
    care_3_b3: "A monthly improvement plan",
    faq_h: "Frequent questions",
    faq_1_q: "What do I need from you?",
    faq_1_a: "Copy, business facts, and if you have them: photos, logo, and links. If not, I’ll help you structure it.",
    faq_2_q: "Will the site be responsive?",
    faq_2_a: "Yes. Everything I deliver works on phone, tablet, and desktop. It is included, not an add-on.",
    faq_3_q: "Does it include a domain or hosting?",
    faq_3_a: "No. Those are yours. I’ll advise you and help you buy them and publish.",
    faq_4_q: "What if I need a store or a large system?",
    faq_4_a: "CRM, SaaS, ops systems, or an online store leave the calculator. Message me on WhatsApp and we’ll check viability.",
    contact_h: "Tell me what you need",
    contact_p: "I’ll prepare a proposal with the breakdown you built above.",
    label_name: "Name",
    label_email: "Email",
    label_message: "Message",
    ph_message: "Context, timing, or questions…",
    send: "Send me your message",
    wa: "Message me on WhatsApp",
    hint: "On send, your email app opens with the breakdown ready. Domain and hosting are not in the range.",
    footer: "All rights reserved.",
    yes: "Yes",
    no: "No",
    "q.type": "Project type",
    "q.type.web": "Website",
    "q.type.landing": "Landing page",
    "q.type.shop": "Online store",
    "q.type.system": "CRM / SaaS / management system",
    "q.type.web.desc": "A multi-section site to present your business: who you are, what you offer, and how to reach you.",
    "q.type.landing.desc": "A single page focused on one goal: getting the visitor to contact, book, or buy one thing.",
    "q.type.shop.desc": "A store with catalog and orders. Too complex to quote here: we’ll review it on WhatsApp.",
    "q.type.system.desc": "A custom system (dashboards, users, data). Not for the calculator: we analyze it on WhatsApp.",
    "q.pages": "How big is your site?",
    "q.pages.help": "Pick whatever is closest to what you need. These are sections within the same site.",
    "q.pages.one": "All on one page",
    "q.pages.one.desc": "A single page with everything. Great to start.",
    "q.pages.basic": "Basic site · about 3 pages",
    "q.pages.basic.desc": "Home, Services, and Contact.",
    "q.pages.standard": "Full site · about 5 pages",
    "q.pages.standard.desc": "Home, About, Services, Gallery, and Contact.",
    "q.pages.wide": "Large site · 7 to 8 pages",
    "q.pages.wide.desc": "The above plus blog, FAQ, or pricing.",
    "q.landingOnly": "A single page",
    "q.forms": "Forms",
    "q.forms.help": "A form collects your clients’ details: contact, bookings, or orders. If unsure, 1 is usually enough.",
    "q.admin": "Site administration",
    "q.admin.help": "Do you want to edit the content yourself, without depending on me?",
    "q.admin.none": "I don’t need it",
    "q.admin.basic": "Basic: edit text and images",
    "q.admin.advanced": "Advanced: products, posts, or users",
    "q.seo": "Show up on Google (SEO)",
    "q.seo.none": "No SEO (people won’t find you on Google)",
    "q.seo.basic": "Essential (titles and description)",
    "q.seo.local": "Local (so people in your city find you)",
    "q.seo.advanced": "Complete (to compete)",
    "q.seo.tip_aria": "What SEO is and what each level includes",
    "q.seo.tip_what": "SEO is how Google finds you when someone searches for what you offer. Without it, your site exists, but almost nobody arrives from search.",
    "q.seo.tip_none": "No SEO: I don’t prepare the site for search engines.",
    "q.seo.tip_basic": "Essential: titles, description, and the minimum so Google can index you.",
    "q.seo.tip_local": "Local: plus guidance so people in your city or neighborhood can find you.",
    "q.seo.tip_advanced": "Complete: structure, speed, and content so you can compete with other businesses.",
    "q.design": "Design",
    "q.design.preset": "Preset / template",
    "q.design.scratch": "From scratch",
    "q.design.help": "Preset starts from a polished template; from scratch is a unique design just for you.",
    "q.identity": "Identity (logo and colors)",
    "q.identity.defined": "I already have it",
    "q.identity.create": "It still needs creating",
    "q.identity.help": "Do you have a logo and brand colors, or do we create them?",
    "q.theme": "Site theme",
    "q.theme.light": "Light only",
    "q.theme.both": "Light and dark",
    "q.theme.help": "Do you want your site to offer a light mode and also a dark mode?",
    "q.languages": "Languages",
    "q.languages.one": "One",
    "q.languages.multi": "Two or more",
    "q.languages.help": "Should your site be in more than one language?",
    "q.images": "Are your images ready?",
    "q.images.help": "We mean photos or graphics already cropped and optimized for web.",
    "q.images.ready": "Yes, they’re ready",
    "q.images.process": "No, please prepare them",
    "q.images.help.ready": "Great: I’ll use your images as they are, at no extra cost.",
    "q.images.help.process": "I adjust format, size, and weight so they load fast and stay sharp (extra work).",
    "q.maintenance": "Care afterwards",
    "q.maintenance.help": "It always has to be done. Maintenance is not new development: new features or sections are quoted separately.",
    "q.maintenance.light": "Light care",
    "q.maintenance.mid": "Steady improvement",
    "q.maintenance.full": "Full accompaniment",
    select: "Select",
  },
};

function tFactory(getLang) {
  return (key) => {
    const lang = getLang();
    return I18N[lang]?.[key] ?? I18N.es[key] ?? key;
  };
}

function applyI18n(root, t) {
  root.querySelectorAll("[data-i18n]").forEach((el) => {
    el.textContent = t(el.getAttribute("data-i18n"));
  });
  root.querySelectorAll("[data-i18n-placeholder]").forEach((el) => {
    el.setAttribute("placeholder", t(el.getAttribute("data-i18n-placeholder")));
  });
  root.querySelectorAll("[data-i18n-aria]").forEach((el) => {
    const label = t(el.getAttribute("data-i18n-aria"));
    el.setAttribute("aria-label", label);
    el.setAttribute("title", label);
  });
  root.querySelectorAll("option[data-i18n]").forEach((el) => {
    el.textContent = t(el.getAttribute("data-i18n"));
  });
}

function initThemeLang({ onLang } = {}) {
  const root = document.documentElement;
  const body = document.body;

  const getLang = () => (root.getAttribute("lang") === "en" ? "en" : "es");
  const t = tFactory(getLang);

  const setLang = (lang) => {
    const next = lang === "en" ? "en" : "es";
    root.setAttribute("lang", next);
    try {
      localStorage.setItem("lang", next);
    } catch (_) {
      /* private mode */
    }
    applyI18n(document, t);
    document.querySelectorAll("[data-lang-toggle]").forEach((btn) => {
      const mark = btn.querySelector("[data-lang-mark]");
      if (mark) mark.textContent = next === "es" ? "EN" : "ES";
    });
    onLang?.(next, t);
  };

  const setTheme = (dark) => {
    body.classList.toggle("theme-obsidian", Boolean(dark));
    try {
      localStorage.setItem("theme", dark ? "dark" : "light");
    } catch (_) {
      /* private mode */
    }
    const label = t(dark ? "theme_to_light" : "theme_to_dark");
    document.querySelectorAll("[data-theme-toggle]").forEach((btn) => {
      btn.setAttribute("aria-label", label);
      btn.setAttribute("title", label);
      btn.setAttribute("aria-pressed", String(Boolean(dark)));
    });
  };

  let savedLang = null;
  let savedTheme = null;
  try {
    savedLang = localStorage.getItem("lang");
    savedTheme = localStorage.getItem("theme");
  } catch (_) {
    /* private mode */
  }
  const prefersDark = window.matchMedia?.("(prefers-color-scheme: dark)").matches;
  setLang(savedLang === "en" ? "en" : "es");
  setTheme(savedTheme ? savedTheme === "dark" : Boolean(prefersDark));

  document.querySelectorAll("[data-lang-toggle]").forEach((btn) => {
    btn.addEventListener("click", () => setLang(getLang() === "es" ? "en" : "es"));
  });
  document.querySelectorAll("[data-theme-toggle]").forEach((btn) => {
    btn.addEventListener("click", () => setTheme(!body.classList.contains("theme-obsidian")));
  });

  return { getLang, t, setLang, setTheme };
}

window.RVLang = { I18N, tFactory, applyI18n, initThemeLang };
